### ISSUE TITLE
Spaces after data in the slots.

### ISSUE THREAD

**Issue by VAFS001** [Makin-Things/platinum-weather-card#36]
Would there by any way to add a space after the data and the unit? Especially in the pressure, wind speed, visibility and precip amounts?

![image](https://user-images.githubusercontent.com/17306997/180107681-2131d38d-f185-40c1-8689-fc8903d5954c.png)

It also seems that the icon is not centered with the temp/feels like data. I might just be nit picking here but it would be nice to have those centered or inline with the other:

![image](https://user-images.githubusercontent.com/17306997/180108058-4c5c914f-aa98-4844-a502-642a8e47ed65.png)

Small things, but if you have time and think they are good ideas that would be awesome.

Thank you

**Comment by VAFS001** [comment]
The card_mod helped a lot. If you make changes to the svg files it will be no issue getting them aligned again.

![image](https://user-images.githubusercontent.com/17306997/180219108-35ffe795-b67f-4c49-a553-68736ed55b66.png)

The css classes I modified were 
.top-left { margin-top: -14px; }
.slot-text { padding-right: 3px; }

It really made a difference.

Once question for you though. How did you get the large text above your description of the day? Looks like it is in place of the separator line.

**Comment by Makin-Things** [comment]
You have to have a sensor that provide a short text description. A lot of the HA weather integrations don't seem to have it. In the integration we use for Australia it is called ``short text``, but it is like the headline summary. If you have it you configure it here.
![image](https://user-images.githubusercontent.com/91187456/180324745-142e1fb4-40e1-464e-82c7-1ce17ee88d86.png)

**Comment by Makin-Things** [comment]
I have tweaked a few icons, but not done a release yet. They will get updated on the next release at which time you probably will want to remove the mod to top-left.

**Comment by Makin-Things** [comment]
Closing as I believe the original issue is resolved. There is a ton of work going on in the background to improve the overall icon set and configuration of conditions.
For more informal chat/questions please use this community thread. Keen for focused issues and reports of problems here though.
https://community.home-assistant.io/t/customising-the-bom-weather-and-lovelace-now-in-hacs

**Comment by PulsarFX** [comment]
my take on scaling down the top left icon to the size of the current temperature:
It also reduces the space between overview and slot section.

```card_mod:
  style: |
    .top-left {
      height: 60px;
      margin-top: 0px;
    }
    .big-icon { 
      height: 100%; 
      width: 100%;
    }
    .overview-section, 
    .slot-section { 
      padding:0;
    }
```

![image](https://user-images.githubusercontent.com/4960210/224441989-2b5a48b7-3f53-421e-a950-671efa43c3ad.png)

**Comment by alanmilinovic** [comment]
Icons are still not aligned or consistent horizontally. Any update on that?
